aiandrox/hashlog

- app/javascript/packs/application.js
- package.json
- yarn.lock
close #146
GoogleAnalyticを導入
- vue-analytics
> GoogleAnalyticを追加

- db/migrate/20201021135324_add_index.rb
- db/schema.rb
> DBにindexを追加

- app/javascript/components/TagsTab.vue
- app/javascript/components/TheRegisterTagDialog.vue
- app/javascript/components/TheTagWrapper.vue
- app/javascript/pages/MyTag.vue
- app/javascript/pages/Mypage.vue
> 戻るボタンを押してもデータの再取得をするようにした

- app/controllers/static_pages_controller.rb
- config/routes.rb
> マイタグページで自分以外のページでは404になるようにした

- app/javascript/components/Profile.vue
- app/javascript/components/ProfileStatus.vue
- app/javascript/pages/Mypage.vue
close #1
fix #1
追加した機能
変更点
画像
- データベース
- gem
- レビュワーに見てほしい点
- 気づき
> [Fix] user.privacyのprops修正

- app/javascript/components/Profile.vue
- app/javascript/components/ProfileStatus.vue
- app/javascript/pages/Mypage.vue
close #1
fix #1
追加した機能
変更点
画像
- データベース
- gem
- レビュワーに見てほしい点
- 気づき
>  [Fix] user.privacyのprops修正

- app/models/registered_tag.rb
- app/models/user.rb
- app/services/twitter_api_job/add_tweets.rb
- spec/models/registered_tag_spec.rb
- spec/services/twitter_api_job/add_tweets_spec.rb
close #1
fix #1
追加した機能
変更点
画像
- データベース
- gem
- レビュワーに見てほしい点
- 気づき
> フラグによって自分のアカウントでsearchするかどうか選ぶ

- app/models/registered_tag.rb
- app/services/twitter_api_job/remind_reply.rb
- spec/models/registered_tag_spec.rb
> [Add] リマインダを送る条件を追加

- app/javascript/components/Profile.vue
リンク先をscreen_nameから取っていたので、twitter_idから取るようにした
> Fix profile twitter id

- app/javascript/pages/Top.vue
> [Add] お知らせを追加

- app/models/registered_tag.rb
- app/models/tweet.rb
> [Fix] ツイート取得時にmediasがnilだったのでエラーが出ていた

- app/javascript/App.vue
- app/javascript/components/Ranking.vue
- app/javascript/pages/Top.vue
- app/javascript/plugins/axios.js
- app/javascript/store/index.js
- app/javascript/store/is-not-found.js
> APIが404のときもNotFoundページを表示する

- app/controllers/api/v1/registered_tags/day_counts_controller.rb
- app/models/registered_tag.rb
- spec/factories/registered_tags.rb
- spec/factories/tweets.rb
- spec/models/registered_tag_spec.rb
- spec/models/tweet_spec.rb
- spec/requests/api/v1/registered_tags/day_counts_spec.rb
- spec/requests/api/v1/registered_tags/persistences_spec.rb
- spec/requests/api/v1/tweets_spec.rb
ツイート数で計算していたので、ツイート日数で計算するようにした
> 日数ランキングを修正

- app/controllers/api/v1/users/current/twitter_data_controller.rb
- app/models/user.rb
- app/services/job/add_tweets.rb
- app/services/job/remind_reply.rb
- app/services/job/update_user_twitter_data.rb
- app/services/twitter_api/user.rb
- config/schedule.rb
- lib/tasks/twitter_cron.rake
- spec/rspec-output
- spec/services/cron_twitter.rb
- spec/services/job/add_tweets_spec.rb
- spec/services/job/remind_reply_spec.rb
- spec/services/twitter_api/user_spec.rb
close #213
あとでherokuのschedulerに登録する
> cronでTwitterアカウントの情報を最新にする

- .rubocop.yml
- app/controllers/api/v1/base_controller.rb
- app/controllers/api/v1/oauths_controller.rb
- app/controllers/concerns/errors_handler.rb
- app/services/logger_helper.rb
- app/services/twitter_api/update.rb
- app/services/twitter_api/user.rb
- app/services/twitter_api/user_tweets.rb
- app/services/twitter_api_client.rb
- config/environments/production.rb
- config/puma.rb
> 224 fix invalid or expired token

- app/models/authentication.rb
- app/models/image.rb
- app/models/registered_tag.rb
- app/models/tweet.rb
- app/models/user.rb
- app/serializers/registered_tag_serializer.rb
- app/serializers/tweet_serializer.rb
- app/serializers/user_serializer.rb
- app/services/cron_twitter.rb
- config/schedule.rb
- db/migrate/20220409060859_add_last_tweeted_at_and_tweet_rate_to_registered_tags.rb
- db/schema.rb
- lib/tasks/auto_annotate_models.rake
- lib/tasks/ranking_cron.rake
- spec/factories/authentications.rb
- spec/factories/registered_tags.rb
- spec/factories/tweets.rb
- spec/factories/users.rb
- spec/models/authentication_spec.rb
- spec/models/registered_tag_spec.rb
- spec/models/tweet_spec.rb
- spec/models/user_spec.rb
- spec/requests/api/v1/registered_tags/day_counts_spec.rb
- spec/requests/api/v1/registered_tags_spec.rb
- spec/services/job/add_tweets_spec.rb
> ランキング用カラムは定期実行で更新するようにした

- app/controllers/api/v1/base_controller.rb
- app/controllers/api/v1/oauths_controller.rb
- app/controllers/concerns/errors_handler.rb
- app/services/twitter_api/update.rb
close #200 の修正
追加した機能
変更点
画像
- データベース
- gem
- レビュワーに見てほしい点
- 気づき
> 200 twitter timeline

- .github/workflows/heroku_deploy.yml
> 自動デプロイできるようにする

- .github/workflows/git_pr_release.yml
- .github/workflows/heroku_deploy.yml
close #1
fix #1
追加した機能
変更点
画像
- データベース
- gem
- レビュワーに見てほしい点
- 気づき
> [Add] リリース用ブランチを自動作成する

- .github/release-drafter.yml
close #1
fix #1
追加した機能
変更点
画像
- データベース
- gem
- レビュワーに見てほしい点
- 気づき
> [Add] test

- .github/workflows/publish-release.yml
> fix release yml

- .github/workflows/release.yml
close #1
fix #1
追加した機能
変更点
画像
- データベース
- gem
- レビュワーに見てほしい点
- 気づき
> デフォルトブランチでリリースするためにジョブを分ける

- .github/workflows/release.yml
> [Fix] Error: Error: Need to provide valid JSON payload を修正

- .github/workflows/release.yml
> [Fix] job失敗時のSlack通知修正
